
services:
  webrtc-detection-app: 
    build: .
    container_name: webrtc_detection_service
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app/server
      - ./client:/usr/src/app/client
      - ./public:/usr/src/app/public
      - ./bench:/usr/src/app/bench
    environment:
      # ✅ FIX: This now reads the MODE variable from your shell (e.g., from start.sh)
      # It will default to 'wasm' if not set.
      - MODE=${MODE:-wasm}
      # Reads the ngrok token from your .env file
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: npm run dev
