version: '3.8'

services:
  webrtc-detection-app:
    build: .
    container_name: webrtc_detection_service
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app/server
      - ./client:/usr/src/app/client
      - ./public:/usr/src/app/public
      - ./bench:/usr/src/app/bench
    environment:
      - MODE=wasm
      # ✅ CORRECT: Reads the token from the .env file
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN} 
    command: npm run dev 