
services:
  webrtc-detection:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MODE=wasm
      - LOG_LEVEL=info
    volumes:
      - ./logs:/app/logs
      - ./metrics.json:/app/metrics.json
    restart: unless-stopped
    
  # Optional: Add nginx for production
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - webrtc-detection
